language: go

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz
  - tar xzf hugo_0.55.6_Linux-64bit.tar.gz

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
