name: CI

on:
  push:
    branches:
      - master
  pull_request: {}
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 6.0.1

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 6.0.1

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
